apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eds-pvc01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: eds-eds-csi-provisioner